/// NVENC SDK 12.2 FFI bindings generated by bindgen from `nvEncodeAPI.h`.
///
/// Struct layouts, field offsets, enum values, and function pointer signatures
/// are all derived directly from the C header via bindgen — no manual
/// transcription. This module re-exports the generated types under clean names
/// and adds Rust helper functions for session management and error reporting.
///
/// Reference: <https://github.com/FFmpeg/nv-codec-headers/blob/n12.2.72.0/include/ffnvcodec/nvEncodeAPI.h>
#[cfg(any(target_os = "windows", test))]
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    clippy::all,
    clippy::pedantic,
    unsafe_op_in_unsafe_fn,
    unnecessary_transmutes,
    unpredictable_function_pointer_comparisons,
    unused_imports,
    dead_code
)]
pub(crate) mod ffi {
    // ── Bindgen-generated types from nvEncodeAPI.h ──
    include!(concat!(env!("OUT_DIR"), "/nvenc_bindings.rs"));

    use std::ffi::c_void;

    // ── GUID constants (defined as `static const GUID` in C header, which
    //    bindgen cannot turn into Rust `const`. Values are copied verbatim
    //    from the header comments.) ──

    pub const NV_ENC_CODEC_H264_GUID: GUID = GUID {
        Data1: 0x6bc82762,
        Data2: 0x4e63,
        Data3: 0x4ca4,
        Data4: [0xaa, 0x85, 0x1e, 0x50, 0xf3, 0x21, 0xf6, 0xbf],
    };

    pub const NV_ENC_CODEC_HEVC_GUID: GUID = GUID {
        Data1: 0x790cdc88,
        Data2: 0x4522,
        Data3: 0x4d7b,
        Data4: [0x94, 0x25, 0xbd, 0xa9, 0x97, 0x5f, 0x76, 0x03],
    };

    pub const NV_ENC_PRESET_P1_GUID: GUID = GUID {
        Data1: 0xfc0a8d3e,
        Data2: 0x45f8,
        Data3: 0x4cf8,
        Data4: [0x80, 0xc7, 0x29, 0x88, 0x71, 0x59, 0x0e, 0xbf],
    };

    pub const NV_ENC_H264_PROFILE_MAIN_GUID: GUID = GUID {
        Data1: 0x60b5c1d4,
        Data2: 0x67fe,
        Data3: 0x4790,
        Data4: [0x94, 0xd5, 0xc4, 0x72, 0x6d, 0x7b, 0x6e, 0x6d],
    };

    pub const NV_ENC_HEVC_PROFILE_MAIN_GUID: GUID = GUID {
        Data1: 0xb514c39a,
        Data2: 0xb55b,
        Data3: 0x40fa,
        Data4: [0x87, 0x8f, 0xf1, 0x25, 0x3b, 0x4d, 0xfd, 0xec],
    };

    // ── Status code re-exports (clean names) ──

    pub const NV_ENC_SUCCESS: NVENCSTATUS = _NVENCSTATUS_NV_ENC_SUCCESS;
    pub const NV_ENC_ERR_NO_ENCODE_DEVICE: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_NO_ENCODE_DEVICE;
    pub const NV_ENC_ERR_UNSUPPORTED_DEVICE: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_UNSUPPORTED_DEVICE;
    pub const NV_ENC_ERR_INVALID_ENCODERDEVICE: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_INVALID_ENCODERDEVICE;
    pub const NV_ENC_ERR_INVALID_DEVICE: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_INVALID_DEVICE;
    pub const NV_ENC_ERR_DEVICE_NOT_EXIST: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_DEVICE_NOT_EXIST;
    pub const NV_ENC_ERR_INVALID_PTR: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_INVALID_PTR;
    pub const NV_ENC_ERR_INVALID_EVENT: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_INVALID_EVENT;
    pub const NV_ENC_ERR_INVALID_PARAM: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_INVALID_PARAM;
    pub const NV_ENC_ERR_INVALID_CALL: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_INVALID_CALL;
    pub const NV_ENC_ERR_OUT_OF_MEMORY: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_OUT_OF_MEMORY;
    pub const NV_ENC_ERR_ENCODER_NOT_INITIALIZED: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_ENCODER_NOT_INITIALIZED;
    pub const NV_ENC_ERR_UNSUPPORTED_PARAM: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_UNSUPPORTED_PARAM;
    pub const NV_ENC_ERR_LOCK_BUSY: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_LOCK_BUSY;
    pub const NV_ENC_ERR_NOT_ENOUGH_BUFFER: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_NOT_ENOUGH_BUFFER;
    pub const NV_ENC_ERR_INVALID_VERSION: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_INVALID_VERSION;
    pub const NV_ENC_ERR_MAP_FAILED: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_MAP_FAILED;
    pub const NV_ENC_ERR_NEED_MORE_INPUT: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_NEED_MORE_INPUT;
    pub const NV_ENC_ERR_ENCODER_BUSY: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_ENCODER_BUSY;
    pub const NV_ENC_ERR_EVENT_NOT_REGISTERD: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_EVENT_NOT_REGISTERD;
    pub const NV_ENC_ERR_GENERIC: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_GENERIC;
    pub const NV_ENC_ERR_INCOMPATIBLE_CLIENT_KEY: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_INCOMPATIBLE_CLIENT_KEY;
    pub const NV_ENC_ERR_UNIMPLEMENTED: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_UNIMPLEMENTED;
    pub const NV_ENC_ERR_RESOURCE_REGISTER_FAILED: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_RESOURCE_REGISTER_FAILED;
    pub const NV_ENC_ERR_RESOURCE_NOT_REGISTERED: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_RESOURCE_NOT_REGISTERED;
    pub const NV_ENC_ERR_RESOURCE_NOT_MAPPED: NVENCSTATUS =
        _NVENCSTATUS_NV_ENC_ERR_RESOURCE_NOT_MAPPED;
    pub const NV_ENC_ERR_NEED_MORE_OUTPUT: NVENCSTATUS = _NVENCSTATUS_NV_ENC_ERR_NEED_MORE_OUTPUT;

    // ── Rate control mode re-exports ──

    pub const NV_ENC_PARAMS_RC_VBR: NV_ENC_PARAMS_RC_MODE =
        _NV_ENC_PARAMS_RC_MODE_NV_ENC_PARAMS_RC_VBR;

    // ── Buffer format re-exports ──

    pub const NV_ENC_BUFFER_FORMAT_ARGB: NV_ENC_BUFFER_FORMAT =
        _NV_ENC_BUFFER_FORMAT_NV_ENC_BUFFER_FORMAT_ARGB;
    pub const NV_ENC_BUFFER_FORMAT_NV12: NV_ENC_BUFFER_FORMAT =
        _NV_ENC_BUFFER_FORMAT_NV_ENC_BUFFER_FORMAT_NV12;

    // ── Device type re-exports ──

    pub const NV_ENC_DEVICE_TYPE_DIRECTX: NV_ENC_DEVICE_TYPE =
        _NV_ENC_DEVICE_TYPE_NV_ENC_DEVICE_TYPE_DIRECTX;

    // ── Input resource type re-exports ──

    pub const NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX: NV_ENC_INPUT_RESOURCE_TYPE =
        _NV_ENC_INPUT_RESOURCE_TYPE_NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX;

    // ── Tuning info re-exports ──

    pub const NV_ENC_TUNING_INFO_ULTRA_LOW_LATENCY: NV_ENC_TUNING_INFO =
        NV_ENC_TUNING_INFO_NV_ENC_TUNING_INFO_ULTRA_LOW_LATENCY;
    pub const NV_ENC_TUNING_INFO_UNDEFINED: NV_ENC_TUNING_INFO =
        NV_ENC_TUNING_INFO_NV_ENC_TUNING_INFO_UNDEFINED;

    // ── Pic type re-exports ──

    pub const NV_ENC_PIC_TYPE_IDR: NV_ENC_PIC_TYPE = _NV_ENC_PIC_TYPE_NV_ENC_PIC_TYPE_IDR;
    pub const NV_ENC_PIC_TYPE_I: NV_ENC_PIC_TYPE = _NV_ENC_PIC_TYPE_NV_ENC_PIC_TYPE_I;

    // ── Pic flag re-exports ──

    pub const NV_ENC_PIC_FLAG_FORCEIDR: u32 = _NV_ENC_PIC_FLAGS_NV_ENC_PIC_FLAG_FORCEIDR as u32;
    pub const NV_ENC_PIC_FLAG_EOS: u32 = _NV_ENC_PIC_FLAGS_NV_ENC_PIC_FLAG_EOS as u32;

    // ── Buffer usage re-exports ──

    pub const NV_ENC_INPUT_IMAGE: NV_ENC_BUFFER_USAGE = _NV_ENC_BUFFER_USAGE_NV_ENC_INPUT_IMAGE;
    pub const NV_ENC_OUTPUT_MOTION_VECTOR: NV_ENC_BUFFER_USAGE =
        _NV_ENC_BUFFER_USAGE_NV_ENC_OUTPUT_MOTION_VECTOR;
    pub const NV_ENC_OUTPUT_BITSTREAM: NV_ENC_BUFFER_USAGE =
        _NV_ENC_BUFFER_USAGE_NV_ENC_OUTPUT_BITSTREAM;
    pub const NV_ENC_OUTPUT_RECON: NV_ENC_BUFFER_USAGE = _NV_ENC_BUFFER_USAGE_NV_ENC_OUTPUT_RECON;

    // ── Version helpers ──

    /// Constructs the version field for an NVENC struct.
    /// Matches the SDK macro: `NVENCAPI_STRUCT_VERSION(ver)`.
    pub const fn nvencapi_struct_version(ver: u32) -> u32 {
        NVENCAPI_VERSION | (ver << 16) | (0x7 << 28)
    }

    /// Version with high bit set — used by some structs in SDK 12.2.
    pub const fn nvencapi_struct_version_high(ver: u32) -> u32 {
        nvencapi_struct_version(ver) | (1 << 31)
    }

    /// Encodes our SDK version in the format returned by `NvEncodeAPIGetMaxSupportedVersion`.
    /// Format: `(major << 4) | minor`.
    pub const fn nvencapi_max_version() -> u32 {
        (NVENCAPI_MAJOR_VERSION << 4) | NVENCAPI_MINOR_VERSION
    }

    /// Decodes a packed max-version value into `(major, minor)`.
    pub const fn unpack_max_version(packed: u32) -> (u32, u32) {
        (packed >> 4, packed & 0xF)
    }

    /// Returns `true` if the driver's max supported version is >= the SDK version we require.
    pub const fn is_driver_version_compatible(driver_max: u32, sdk_required: u32) -> bool {
        driver_max >= sdk_required
    }

    // ── Custom Default impls (bindgen generates zero-init defaults, but some
    //    structs need their version field set) ──

    impl _NV_ENC_OPEN_ENCODE_SESSIONEX_PARAMS {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version(1);
            s.apiVersion = NVENCAPI_VERSION;
            s
        }
    }

    impl _NV_ENC_INITIALIZE_PARAMS {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version_high(7);
            s
        }
    }

    impl _NV_ENC_CONFIG {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version_high(9);
            s
        }
    }

    impl _NV_ENC_PRESET_CONFIG {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version_high(5);
            s.presetCfg.version = nvencapi_struct_version_high(9);
            s
        }
    }

    impl _NV_ENC_PIC_PARAMS {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version_high(7);
            s
        }
    }

    impl _NV_ENC_REGISTER_RESOURCE {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version(5);
            s
        }
    }

    impl _NV_ENC_MAP_INPUT_RESOURCE {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version(4);
            s
        }
    }

    impl _NV_ENC_LOCK_BITSTREAM {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version_high(2);
            s
        }
    }

    impl _NV_ENC_CREATE_BITSTREAM_BUFFER {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version(1);
            s
        }
    }

    impl _NV_ENCODE_API_FUNCTION_LIST {
        pub fn new_versioned() -> Self {
            let mut s = Self::default();
            s.version = nvencapi_struct_version(2);
            s
        }
    }

    // ── Entry points (loaded dynamically from DLL) ──

    pub type PFnNvEncodeAPICreateInstance =
        unsafe extern "system" fn(function_list: *mut NV_ENCODE_API_FUNCTION_LIST) -> NVENCSTATUS;

    pub type PFnNvEncodeAPIGetMaxSupportedVersion =
        unsafe extern "system" fn(version: *mut u32) -> NVENCSTATUS;

    /// Opens an NVENC encode session after validating driver version compatibility.
    ///
    /// Encapsulates the version check and session creation so it can be tested
    /// with mock NVENC functions on any platform.
    ///
    /// # Safety
    ///
    /// `open_session_fn` must be a valid NVENC function pointer (or a safe mock).
    /// `device_ptr` must be a valid device pointer for the given `device_type`.
    ///
    /// # Errors
    ///
    /// - [`VideoError::DriverVersionTooOld`] if `driver_max_version < nvencapi_max_version()`
    /// - [`VideoError::EncodingFailed`] if the open-session call returns a non-success status
    pub unsafe fn open_session(
        driver_max_version: u32,
        open_session_fn: PNVENCOPENENCODESESSIONEX,
        device_ptr: *mut c_void,
        device_type: NV_ENC_DEVICE_TYPE,
    ) -> Result<*mut c_void, crate::encoder::VideoError> {
        if !is_driver_version_compatible(driver_max_version, nvencapi_max_version()) {
            let (drv_maj, drv_min) = unpack_max_version(driver_max_version);
            return Err(crate::encoder::VideoError::DriverVersionTooOld {
                driver_version: format!("{drv_maj}.{drv_min}"),
                sdk_version: format!("{NVENCAPI_MAJOR_VERSION}.{NVENCAPI_MINOR_VERSION}"),
            });
        }

        let mut params = NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS::new_versioned();
        params.device = device_ptr;
        params.deviceType = device_type;

        let mut encoder: *mut c_void = std::ptr::null_mut();
        let open_fn =
            open_session_fn.ok_or_else(|| crate::encoder::VideoError::EncodingFailed {
                reason: "nvEncOpenEncodeSessionEx function pointer is null".to_string(),
            })?;
        let status = unsafe { open_fn(&raw mut params, &raw mut encoder) };

        if status != NV_ENC_SUCCESS {
            return Err(crate::encoder::VideoError::EncodingFailed {
                reason: format!(
                    "nvEncOpenEncodeSession failed: {} (status={})",
                    nvenc_status_to_string(status),
                    status
                ),
            });
        }

        Ok(encoder)
    }

    /// Converts NVENC status code to human-readable string.
    pub fn nvenc_status_to_string(status: NVENCSTATUS) -> String {
        match status {
            NV_ENC_SUCCESS => "NV_ENC_SUCCESS".to_string(),
            NV_ENC_ERR_NO_ENCODE_DEVICE => "NV_ENC_ERR_NO_ENCODE_DEVICE".to_string(),
            NV_ENC_ERR_UNSUPPORTED_DEVICE => "NV_ENC_ERR_UNSUPPORTED_DEVICE".to_string(),
            NV_ENC_ERR_INVALID_ENCODERDEVICE => "NV_ENC_ERR_INVALID_ENCODERDEVICE".to_string(),
            NV_ENC_ERR_INVALID_DEVICE => "NV_ENC_ERR_INVALID_DEVICE".to_string(),
            NV_ENC_ERR_DEVICE_NOT_EXIST => "NV_ENC_ERR_DEVICE_NOT_EXIST".to_string(),
            NV_ENC_ERR_INVALID_PTR => "NV_ENC_ERR_INVALID_PTR".to_string(),
            NV_ENC_ERR_INVALID_EVENT => "NV_ENC_ERR_INVALID_EVENT".to_string(),
            NV_ENC_ERR_INVALID_PARAM => "NV_ENC_ERR_INVALID_PARAM".to_string(),
            NV_ENC_ERR_INVALID_CALL => "NV_ENC_ERR_INVALID_CALL".to_string(),
            NV_ENC_ERR_OUT_OF_MEMORY => "NV_ENC_ERR_OUT_OF_MEMORY".to_string(),
            NV_ENC_ERR_ENCODER_NOT_INITIALIZED => "NV_ENC_ERR_ENCODER_NOT_INITIALIZED".to_string(),
            NV_ENC_ERR_UNSUPPORTED_PARAM => "NV_ENC_ERR_UNSUPPORTED_PARAM".to_string(),
            NV_ENC_ERR_LOCK_BUSY => "NV_ENC_ERR_LOCK_BUSY".to_string(),
            NV_ENC_ERR_NOT_ENOUGH_BUFFER => "NV_ENC_ERR_NOT_ENOUGH_BUFFER".to_string(),
            NV_ENC_ERR_INVALID_VERSION => "NV_ENC_ERR_INVALID_VERSION".to_string(),
            NV_ENC_ERR_MAP_FAILED => "NV_ENC_ERR_MAP_FAILED".to_string(),
            NV_ENC_ERR_NEED_MORE_INPUT => "NV_ENC_ERR_NEED_MORE_INPUT".to_string(),
            NV_ENC_ERR_ENCODER_BUSY => "NV_ENC_ERR_ENCODER_BUSY".to_string(),
            NV_ENC_ERR_EVENT_NOT_REGISTERD => "NV_ENC_ERR_EVENT_NOT_REGISTERD".to_string(),
            NV_ENC_ERR_GENERIC => "NV_ENC_ERR_GENERIC".to_string(),
            NV_ENC_ERR_INCOMPATIBLE_CLIENT_KEY => "NV_ENC_ERR_INCOMPATIBLE_CLIENT_KEY".to_string(),
            NV_ENC_ERR_UNIMPLEMENTED => "NV_ENC_ERR_UNIMPLEMENTED".to_string(),
            NV_ENC_ERR_RESOURCE_REGISTER_FAILED => {
                "NV_ENC_ERR_RESOURCE_REGISTER_FAILED".to_string()
            }
            NV_ENC_ERR_RESOURCE_NOT_REGISTERED => "NV_ENC_ERR_RESOURCE_NOT_REGISTERED".to_string(),
            NV_ENC_ERR_RESOURCE_NOT_MAPPED => "NV_ENC_ERR_RESOURCE_NOT_MAPPED".to_string(),
            NV_ENC_ERR_NEED_MORE_OUTPUT => "NV_ENC_ERR_NEED_MORE_OUTPUT".to_string(),
            _ => format!("UNKNOWN_NVENC_ERROR (code {status})"),
        }
    }

    #[cfg(test)]
    mod tests;
}

#[cfg(any(target_os = "windows", test))]
#[allow(unused_imports)] // Used by nvenc.rs on Windows but appears unused on other platforms
pub(crate) use ffi::*;
